"""empty message

Revision ID: 62965f160359
Revises: b1a14b015157
Create Date: 2020-07-03 22:34:07.202903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62965f160359'
down_revision = 'b1a14b015157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    op.drop_column('users', 'passwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwd', mysql.TEXT(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
