"""empty message

Revision ID: b1a14b015157
Revises: 6c76ce44c356
Create Date: 2020-07-03 22:25:49.809014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1a14b015157'
down_revision = '6c76ce44c356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwd', sa.Text(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.TEXT(), nullable=True))
    op.drop_column('users', 'passwd')
    # ### end Alembic commands ###
